user  nginx;
worker_processes  1;          # VPS 1 vCPU
worker_rlimit_nofile 4096;

events {
    worker_connections  512;
    multi_accept        on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile         on;
    tcp_nopush       on;
    tcp_nodelay      on;
    keepalive_timeout 30;
    client_max_body_size 10m;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/xml+rss;

    include /etc/nginx/conf.d/*.conf;
}
